USE [Bank]
GO
CREATE TABLE PERSONAS
(
	PERSONAID INT NOT NULL,
	CORREO VARCHAR(150) NULL,
	ESTADO BIT DEFAULT 1,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(100) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO VARCHAR(15) NULL,
	NRO_DOCUMENTO INT NOT NULL,
	TIPO_DOCUMENTO INT NOT NULL,
	AUDI_FECHCREACION DATETIME DEFAULT GETDATE(),
	AUDI_USERCREADOR VARCHAR(50) NOT NULL,
	AUDI_FECHMODIFICACION DATETIME  NULL,
	AUDI_USERMODIFICADOR VARCHAR(50) NULL
);


