USE [Bank]
GO
CREATE TABLE COMPONENTES
(
	COMPONENTEID INT NOT NULL,
	COMPONENTEPADREID INT NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	ESTADO BIT DEFAULT 1,
	AUDI_FECHCREACION DATETIME DEFAULT GETDATE(),
	AUDI_USERCREADOR VARCHAR(50) NOT NULL,
	AUDI_FECHMODIFICACION DATETIME  NULL,
	AUDI_USERMODIFICADOR VARCHAR(50) NULL
);

