USE [Bank]
GO
CREATE TABLE EMPLEADOS
(
	EMPLEADOID INT NOT NULL,
	PERSONAID INT NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(250) NOT NULL,
	FECHA_CONTRATACION DATE NOT NULL,
	FECHA_FINCONTRATACION DATE NOT NULL,
	ESTADO BIT DEFAULT 1,
	AUDI_FECHCREACION DATETIME DEFAULT GETDATE(),
	AUDI_USERCREADOR VARCHAR(50) NOT NULL,
	AUDI_FECHMODIFICACION DATETIME  NULL,
	AUDI_USERMODIFICADOR VARCHAR(50) NULL
);


