USE [Bank]
GO

CREATE PROCEDURE PERSONAS_SDUNREG
	@PERSONAID INT
	,@CORREO VARCHAR(150)
	,@ESTADO BIT
	,@NOMBRE VARCHAR(50)
	,@APELLIDOS VARCHAR(100)
	,@FECHA_NACIMIENTO DATE
	,@TELEFONO VARCHAR(15)
	,@NRO_DOCUMENTO INT
	,@TIPO_DOCUMENTO INT
	,@AUDI_USERMODIFICADOR VARCHAR(50)
AS

UPDATE [dbo].[PERSONAS]
   SET [CORREO] = ISNULL(@CORREO, [CORREO])
      ,[ESTADO] = ISNULL(@ESTADO, [ESTADO])
      ,[NOMBRE] = ISNULL(@NOMBRE, [NOMBRE])
      ,[APELLIDOS] = ISNULL(@APELLIDOS, [APELLIDOS])
      ,[FECHA_NACIMIENTO] = ISNULL(@FECHA_NACIMIENTO, [FECHA_NACIMIENTO])
      ,[TELEFONO] = ISNULL(@TELEFONO, [TELEFONO])
      ,[NRO_DOCUMENTO] = ISNULL(@NRO_DOCUMENTO, [NRO_DOCUMENTO])
      ,[TIPO_DOCUMENTO] = ISNULL(@TIPO_DOCUMENTO, [TIPO_DOCUMENTO])
      ,[AUDI_FECHMODIFICACION] = GETDATE()
      ,[AUDI_USERMODIFICADOR] = @AUDI_USERMODIFICADOR
	WHERE [PERSONAID] = @PERSONAID
GO


